name: Build and Install Python
author: MatteoH2O1999
description: Action to build any Python version on the latest labels and install it into the local tool cache.
branding:
  icon: play-circle
  color: blue
inputs:
  python-version:
    description: Version range or exact version of Python to use, using SemVer's version range syntax.
  python-version-file:
    description: "File containing the Python version to use. Example: .python-version"
  architecture:
    description: The target architecture (x86, x64) of the Python interpreter.
  check-latest:
    description: "Set this option if you want the action to check for the latest available version that satisfies the version spec."
    default: false
  cache-build:
    required: false
    description: Whether to cache the built Python distribution to speed up successive runs.
    default: false
  allow-build:
    required: false
    description: "Set the behavior of the actoin when actions/setup-python fails and has to build from source. Supported values: allow, info, warn, error, force"
    default: warn
  token:
    description: "The token used to authenticate when fetching Python distributions from https://github.com/actions/python-versions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting."
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  allow-prereleases:
    description: "When 'true', a version range passed to 'python-version' input will match prerelease versions if no GA versions are found. Only 'x.y' version range is supported for CPython."
    default: false
outputs:
  python-version:
    description: The parsed (and eventually built) python version
  architecture:
    description: The target architecture (x86, x64) of the Python interpreter.
runs:
  using: node20
  main: dist/index.js