name: Update JSON Data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  NODE_VERSION: 24

jobs:
  update_cpython_tags:
    runs-on: ubuntu-latest
    name: Update CPython JSON tags and trees
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: master
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Update JSON data
        run: |
          node ./.github/scripts/generate_tags.js
          node ./.github/scripts/generate_trees.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update jest snapshots
        run: npm run test-ci -- -u
        env:
          FORCE_COLOR: 3
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update CPython JSON data
          branch: create-pull-request/cpython-json
          delete-branch: true
          title: Update CPython JSON data
          body: |
            Automated JSON data update by [update_json.yml](https://github.com/MatteoH2O1999/build-and-install-python/tree/master/.github/workflows/update_json.yml)
          assignees: ${{ github.repository_owner }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

  audit_dependencies:
    runs-on: ubuntu-latest
    name: Audit dependencies
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: master
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Audit dependencies
        run: npm audit || true
      - name: Fix dependencies vulnerabilities
        run: npm audit fix || true
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Audit dependencies
          branch: create-pull-request/audit-dependencies
          delete-branch: true
          title: Fix dependencies vulnerabilities
          body: |
            Automated dependencies fix by [update_json.yml](https://github.com/MatteoH2O1999/build-and-install-python/tree/master/.github/workflows/update_json.yml)
          assignees: ${{ github.repository_owner }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
