name: Update JSON Data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update_cpython_tags:
    runs-on: ubuntu-latest
    name: Update CPython JSON tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Update JSON data
        run: node ./.github/scripts/generate_tags.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update CPython JSON tags data
          branch: create-pull-request/cpython-json-tags
          delete-branch: true
          title: Update CPython JSON tags data
          body: |
            Automated JSON data update by [update_json.yml](https://github.com/MatteoH2O1999/build-and-install-python/tree/master/.github/workflows/update_json.yml)
          assignees: ${{ github.repository_owner }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
